<template>
  <div class="home stack-page">
    <div class="swap-container">
      <div class="panel-container inner-container">
        <div class="panel stake-panel">
          <h1 class="panel-title">Add Liquidity</h1>
          <div class="panel-content swap-panel-content liquidity-box-main">
            <div class="panel-header">
              <div class="panel-explanation">USDC-CAPL Liqudity Pool</div>
            </div>
            <div class="panel-display swap-panel-display">
              <div>
                <div class="panel-explanation"><span>amount</span></div>
                <div class="panel-explanation">
                  <input
                    type="text"
                    @input="onChange()"
                    v-model="caplLiquidity"
                    class="input-custom"
                    placeholder="0.00"
                  />
                </div>
              </div>
              <div class="text-right">
                <div class="panel-explanation"><span>My Balance</span></div>
                <div class="panel-explanation myBalance" @click="insertBalanceCAPL">
                  <a>{{ caplBalance.toFixed(4) }} CAPL</a>
                </div>
              </div>
            </div>
            <div class="panel-display swap-panel-display">
              <div>
                <div class="panel-explanation"><span>amount</span></div>
                <div class="panel-explanation">
                  <input
                    type="text"
                    @input="onChange()"
                    v-model="usdcLiquidity"
                    class="input-custom"
                    placeholder="0.00"
                  />
                </div>
              </div>
              <div class="text-right">
                <div class="panel-explanation"><span>My Balance</span></div>
                <div class="panel-explanation myBalance" @click="insertBalanceUSDC">
                  <a>{{ usdcBalance.toFixed(4) }} USDC</a>
                </div>
              </div>
            </div>
            <button
              type="submit"
              @click="handleAddLiquidity()"
              :class="addLiquidityButtonClassNameForState"
              :disabled="addLiquidityButtonDisabled"
            >
              {{ addLiquidityButtonString }}
            </button>
            <div class="explainer">
              Deposit any combination of USDC and/or CAPL tokens into the liquidity pool. 
              Liquidity providers earn a portion of swap fees (0.3%) generated by users.
              Want to earn more? Consider <router-link to="stake" class="button">Staking</router-link> your tokens.
            </div>
          </div>
        </div>
      </div>
      <DappFooter />
    </div>
  </div>
</template>

<script setup lang="ts">
import DappFooter from "@/components/DappFooter.vue";
import { ref, Ref, watchEffect, computed } from "vue";
import { useStore } from "@/store";
import { 
  checkAllAllowances,
  validateInput,
} from "@/utils";
import { checkConnection, checkAvailability } from "@/utils/notifications";

const store: any = useStore();
let usdcLiquidity: Ref<number> = ref(0);
let caplLiquidity: Ref<number> = ref(0);

let approvalFlag: Ref<string | null> = ref("");
let addLiquidityButtonString: Ref<string> = ref("Add Liquidity");
let addLiquidityButtonDisabled = ref(true);
let addLiquidityButtonClassNameForState: Ref<string> = ref("btn-custom-gray");

const isUserConnected = computed(
  () => store.getters["accounts/isUserConnected"]
);

const caplBalance = computed(() => store.getters["tokens/getCAPLBalance"]);
const usdcBalance = computed(() => store.getters["tokens/getUSDCBalance"]);

watchEffect(async () => {
  if (validateInput((usdcLiquidity.value).toString())) {
    usdcLiquidity.value = Number(parseFloat((usdcLiquidity.value).toString()).toFixed(6));
  }

  if (validateInput((caplLiquidity.value).toString())) {
    caplLiquidity.value = Number(parseFloat((caplLiquidity.value).toString()).toFixed(18));
  }

  if (!isUserConnected.value) {
    return;
  }
  if (
    checkAvailability(caplLiquidity.value, caplBalance.value) &&
    checkAvailability(usdcLiquidity.value, usdcBalance.value)
  ) {
    if (
      Number(caplLiquidity.value) === 0 &&
      Number(usdcLiquidity.value) === 0
    ) {
      addLiquidityButtonDisabled.value = true;
      addLiquidityButtonString.value = "Add Liquidity";
      addLiquidityButtonClassNameForState.value = "btn-custom-gray";
    } else {
      addLiquidityButtonDisabled.value = false;
      const { approvalRequired, flag } = await checkAllAllowances(store, [
        Number(usdcLiquidity.value),
        Number(caplLiquidity.value),
      ]);

      approvalFlag.value = flag;

      approvalRequired
        ? ((addLiquidityButtonString.value = "Approve"),
          (addLiquidityButtonClassNameForState.value = "btn-custom"))
        : ((addLiquidityButtonString.value = "Add Liquidity"),
          (addLiquidityButtonClassNameForState.value = "btn-custom-green"));
    }
  } else {
    addLiquidityButtonDisabled.value = true;
    addLiquidityButtonClassNameForState.value = "btn-custom-gray";
  }
});

// handles swapping button logic, dependant on current string

// handles adding liquidity button logic, dependant on current string
// we can assume that if usdcLiquidity > 0 then caplLiquidity > 0
const handleAddLiquidity = async () => {
  if (checkConnection(store)) {
    addLiquidityButtonString.value == "Add Liquidity"
      ? await addLiquidity()
      : await approveAll();
  }
};

// handles three cases
// 1. USDC Approvals, 2. CAPL approvals, 3. Both tokens approvals
// TODO: Refactor these store.dispatch calls into individual functions
const approveAll = async () => {
  if (!approvalFlag.value) return;

  if (approvalFlag.value == "USDC") {
    await store.dispatch("tokens/approveBalancerVault", {
      symbol: "USDC",
    });
  } else if (approvalFlag.value == "CAPL") {
    await store.dispatch("tokens/approveBalancerVault", {
      symbol: "CAPL",
    });
  } else {
    await store.dispatch("tokens/approveBalancerVault", {
      symbol: "USDC",
    });
    await store.dispatch("tokens/approveBalancerVault", {
      symbol: "CAPL",
    });
  }
};

function addLiquidity() {
  store.dispatch("balancer/addLiquidity", {
    caplAmount: Number(caplLiquidity.value),
    usdcAmount: Number(usdcLiquidity.value),
  });
}

function onChange() {
  checkConnection(store);
}

const insertBalanceCAPL = () => {
  caplLiquidity.value = caplBalance.value;
};

const insertBalanceUSDC = () => {
  usdcLiquidity.value = usdcBalance.value;
};

</script>

<style>
.swap-container {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  width: 100%;
  height: 100%;
}
.liquidity-box-main {
  width: 60%;
  margin: 0 auto;
}
.inner-container {
  margin-top: 90px;
}

.panel-container {
  display: flex;
  flex-direction: row;
  justify-content: space-around;
}

.panel {
  flex: 1;
  margin: 0 8%;
}

.panel-title {
  text-align: center;
}

.panel-content {
  border: 1px solid #000000;
  padding: 10px 20px;
  display: flex;
  flex-direction: column;
  justify-content: space-around;
}

.panel-header {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

.panel-display {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  padding: 10px 15px;
  margin: 20px 0;
  border: 2px solid #000000;
}

.btn-switch {
  width: 50px;
  height: 40px;
  margin: auto;
}

.text-right {
  text-align: right;
}
.input-custom {
  display: inline-block;
  padding: 0px;
  margin-top: 10px;
  border-radius: 20px;
  background: transparent;
  border: 2px solid #ff8900;
  text-align: center;
  font-weight: bold;
  color: #2f2c23;
  font-size: 22px;
  max-width: 150px;
  margin: 0 auto 35px auto;
}

/* @media only screen and (max-width: 575px) {
  .panel-container {
    flex-direction: column;
  }
}

@media only screen and (max-width: 575px) {
  .panel-content.swap-panel-content {
    padding: 25px 30px 25px 30px;
  }
} */
</style>
